//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.02 at 02:47:50 PM CEST 
//


package com.example.isprojectjava.model.soap;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for statistics complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="statistics">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="numberOfPlayersByTag" type="{http://example.com/isprojectjava/model/soap}Statistic" maxOccurs="unbounded"/>
 *         &lt;element name="numberOfGamesByPrice" type="{http://example.com/isprojectjava/model/soap}Statistic" maxOccurs="unbounded"/>
 *         &lt;element name="numberOfGamesByYear" type="{http://example.com/isprojectjava/model/soap}Statistic" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "statistics", propOrder = {
    "numberOfPlayersByTag",
    "numberOfGamesByPrice",
    "numberOfGamesByYear"
})
public class Statistics {

    @XmlElement(required = true)
    protected List<Statistic> numberOfPlayersByTag;
    @XmlElement(required = true)
    protected List<Statistic> numberOfGamesByPrice;
    @XmlElement(required = true)
    protected List<Statistic> numberOfGamesByYear;

    /**
     * Gets the value of the numberOfPlayersByTag property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the numberOfPlayersByTag property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNumberOfPlayersByTag().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Statistic }
     * 
     * 
     */
    public List<Statistic> getNumberOfPlayersByTag() {
        if (numberOfPlayersByTag == null) {
            numberOfPlayersByTag = new ArrayList<Statistic>();
        }
        return this.numberOfPlayersByTag;
    }

    /**
     * Gets the value of the numberOfGamesByPrice property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the numberOfGamesByPrice property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNumberOfGamesByPrice().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Statistic }
     * 
     * 
     */
    public List<Statistic> getNumberOfGamesByPrice() {
        if (numberOfGamesByPrice == null) {
            numberOfGamesByPrice = new ArrayList<Statistic>();
        }
        return this.numberOfGamesByPrice;
    }

    /**
     * Gets the value of the numberOfGamesByYear property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the numberOfGamesByYear property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNumberOfGamesByYear().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Statistic }
     * 
     * 
     */
    public List<Statistic> getNumberOfGamesByYear() {
        if (numberOfGamesByYear == null) {
            numberOfGamesByYear = new ArrayList<Statistic>();
        }
        return this.numberOfGamesByYear;
    }

}
