-- Tags import
INSERT INTO tag VALUES(1, 'RPG');
INSERT INTO tag VALUES(2, 'FPS');
INSERT INTO tag VALUES(3, 'ACTION');
INSERT INTO tag VALUES(4, 'STRATEGY');
INSERT INTO tag VALUES(5, 'HORROR');

-- Roles import
INSERT INTO role VALUES(1, 'USER');
INSERT INTO role VALUES(2, 'MANAGER');
INSERT INTO role VALUES(3, 'ADMIN');
